spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SampleRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs



  liquibase:
    enabled: true
    url: jdbc:oracle:thin:@localhost:1521:XE
    user: fatima
    password: 123456
    change-log: classpath:master.xml

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    database: oracle
    show-sql: true

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: fatima
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: userManagement

server:
  port: 8081
